package com.openclaw.canalweb.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.openclaw.canalweb.domain.DatasourceConfig;
import com.openclaw.canalweb.domain.SyncTask;
import com.openclaw.canalweb.domain.TaskFieldMapping;
import com.openclaw.canalweb.domain.TaskTargetConfig;
import org.springframework.stereotype.Service;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class CanalAdapterService {
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    public AdapterRuntimeFiles buildRuntimeFiles(SyncTask task, DatasourceConfig datasource, List<TaskFieldMapping> mappings,
                                                 List<TaskTargetConfig> targetConfig) {
        Map<String, String> config = targetConfig.stream()
                .collect(Collectors.toMap(TaskTargetConfig::configKey, item -> item.configValue() == null ? "" : item.configValue(),
                        (left, right) -> right));
        String type = task.targetType() == null ? "LOGGER" : task.targetType().toUpperCase();
        String key = valueOrDefault(config.get("adapterKey"), task.id());
        String outerAdapter = outerAdapterBlock(type, key, task.id(), config);
        String mappingDir = mappingDir(type, config);
        String mappingFile = task.id() + ".yml";
        String mappingContent = mappingContent(type, task, datasource, mappings, config, key);
        return new AdapterRuntimeFiles(datasource.canalDestination(), outerAdapter, mappingDir, mappingFile, mappingContent);
    }

    public String buildCanalConfig(SyncTask task, DatasourceConfig datasource, List<TaskFieldMapping> mappings,
                                   List<TaskTargetConfig> targetConfig) {
        String mappingBlock = enabledMappings(mappings).stream()
                .map(item -> "        " + item.sourceField() + ": " + item.targetField())
                .collect(Collectors.joining("\n"));
        String fieldOptionsBlock = fieldOptionsBlock(mappings, "        ");
        String targetBlock = targetConfig.stream()
                .map(item -> "  " + item.configKey() + ": \"" + escapeYaml(item.configValue()) + "\"")
                .collect(Collectors.joining("\n"));

        return """
                # Generated by canal-web. Task: %s
                destination: %s
                groupId: g1
                outerAdapterKey: %s
                syncMode: %s
                dataSource:
                  key: %s
                  host: %s
                  port: %d
                  database: %s
                target:
                  type: %s
                %s
                sql: |-
                %s
                mapping:
                %s
                fieldOptions:
                %s
                """.formatted(
                task.taskName(),
                datasource.canalDestination(),
                task.id(),
                task.syncMode(),
                datasource.dataSourceKey(),
                datasource.host(),
                datasource.port(),
                datasource.dbName(),
                task.targetType(),
                targetBlock.isBlank() ? "  config: \"\"" : targetBlock,
                indentSql(task.syncSql()),
                mappingBlock.isBlank() ? "        _empty: _empty" : mappingBlock,
                fieldOptionsBlock.isBlank() ? "        _empty: {}" : fieldOptionsBlock
        );
    }

    private static String outerAdapterBlock(String type, String key, String taskId, Map<String, String> config) {
        if ("KAFKA".equals(type) || "ROCKETMQ".equals(type) || "RABBITMQ".equals(type) || "PULSAR".equals(type) || "PULSARMQ".equals(type) || "LOGGER".equals(type)) {
            return "                      - name: logger\n";
        }
        if ("REDIS".equals(type)) {
            return """
                                  - name: custom-redis
                                    key: %s
                                    properties:
                                      destination: %s
                                      groupId: g1
                                      sourceDatabase: %s
                                      sourceTable: %s
                                      host: %s
                                      port: %s
                                      password: "%s"
                                      database: %s
                                      keyPattern: "%s"
                                      valueType: %s
                                      ttlSeconds: %s
                                      deletePolicy: %s
                                      mappingFile: "%s"
                            """.formatted(
                    key,
                    value(config.get("destination")),
                    value(config.get("sourceDatabase")),
                    valueOrDefault(config.get("sourceTable"), "user_profile"),
                    valueOrDefault(config.get("host"), "127.0.0.1"),
                    valueOrDefault(config.get("port"), "6379"),
                    escapeYaml(value(config.get("password"))),
                    valueOrDefault(config.get("database"), "0"),
                    escapeYaml(valueOrDefault(config.get("keyPattern"), legacyRedisKeyPattern(config))),
                    valueOrDefault(config.get("valueType"), "HASH"),
                    valueOrDefault(config.get("ttlSeconds"), valueOrDefault(config.get("expireSeconds"), "0")),
                    valueOrDefault(config.get("deletePolicy"), "DELETE_KEY"),
                    escapeYaml(valueOrDefault(config.get("mappingFile"), "../conf/custom-redis/" + taskId + ".yml"))
            );
        }
        if ("ES".equals(type) || "ELASTICSEARCH".equals(type)) {
            String adapterName = valueOrDefault(config.get("adapterName"), "es8");
            if ("custom-es".equals(adapterName)) {
                return """
                                      - name: custom-es
                                        key: %s
                                        hosts: %s
                                        properties:
                                          destination: %s
                                          groupId: g1
                                          sourceDatabase: %s
                                          sourceTable: %s
                                          index: %s
                                          documentId: %s
                                          deletePolicy: %s
                                          security.auth: %s
                                          mappingFile: "%s"
                                """.formatted(
                        key,
                        normalizeEsHosts(config.get("hosts")),
                        value(config.get("destination")),
                        value(config.get("sourceDatabase")),
                        valueOrDefault(config.get("sourceTable"), "user_profile"),
                        valueOrDefault(config.get("index"), valueOrDefault(config.get("indexName"), "target_index")),
                        normalizeEsDocumentId(config),
                        valueOrDefault(config.get("deletePolicy"), "DELETE_DOCUMENT"),
                        value(config.get("securityAuth")),
                        escapeYaml(valueOrDefault(config.get("mappingFile"), "../conf/custom-es/" + taskId + ".yml"))
                );
            }
            return """
                                  - name: %s
                                    key: %s
                                    hosts: %s
                                    properties:
                                      mode: %s
                                      cluster.name: %s
                                      security.auth: %s
                            """.formatted(
                    adapterName,
                    key,
                    normalizeEsHosts(config.get("hosts")),
                    valueOrDefault(config.get("mode"), "rest"),
                    valueOrDefault(config.get("clusterName"), "elasticsearch"),
                    value(config.get("securityAuth"))
            );
        }
        if ("HBASE".equals(type)) {
            return """
                                  - name: hbase
                                    key: %s
                                    properties:
                                      hbase.zookeeper.quorum: %s
                                      hbase.zookeeper.property.clientPort: %s
                                      zookeeper.znode.parent: %s
                            """.formatted(
                    key,
                    valueOrDefault(config.get("zkQuorum"), "127.0.0.1"),
                    valueOrDefault(config.get("zkClientPort"), "2181"),
                    valueOrDefault(config.get("zkParent"), "/hbase")
            );
        }
        if ("TABLESTORE".equals(type)) {
            return """
                                  - name: tablestore
                                    key: %s
                                    properties:
                                      endpoint: %s
                                      instance.name: %s
                                      access.key.id: %s
                                      access.key.secret: %s
                            """.formatted(
                    key,
                    value(config.get("endpoint")),
                    value(config.get("instanceName")),
                    value(config.get("accessKeyId")),
                    value(config.get("accessKeySecret"))
            );
        }
        if ("CLICKHOUSE".equals(type)) {
            return jdbcOuterAdapter("clickhouse", key, "ru.yandex.clickhouse.ClickHouseDriver",
                    "jdbc:clickhouse://127.0.0.1:8123/default", config);
        }
        return jdbcOuterAdapter("rdb", key, defaultDriver(type), defaultJdbcUrl(type), config);
    }

    private static String jdbcOuterAdapter(String name, String key, String defaultDriver, String defaultUrl,
                                           Map<String, String> config) {
        return """
                              - name: %s
                                key: %s
                                properties:
                                  jdbc.driverClassName: %s
                                  jdbc.url: "%s"
                                  jdbc.username: "%s"
                                  jdbc.password: "%s"
                                  threads: %s
                                  commitSize: %s
                                  batchSize: %s
                                  scheduleTime: %s
                        """.formatted(
                name,
                key,
                valueOrDefault(config.get("driverClassName"), defaultDriver),
                escapeYaml(valueOrDefault(config.get("jdbcUrl"), defaultUrl)),
                escapeYaml(value(config.get("username"))),
                escapeYaml(value(config.get("password"))),
                valueOrDefault(config.get("threads"), "1"),
                valueOrDefault(config.get("commitSize"), "3000"),
                valueOrDefault(config.get("batchSize"), "3000"),
                valueOrDefault(config.get("scheduleTime"), "600")
        );
    }

    private static String mappingDir(String type, Map<String, String> config) {
        if ("ES".equals(type) || "ELASTICSEARCH".equals(type)) {
            if ("custom-es".equals(valueOrDefault(config.get("adapterName"), "es8"))) {
                return "custom-es";
            }
            return "es8";
        }
        if ("CLICKHOUSE".equals(type)) {
            return "clickhouse";
        }
        if ("KAFKA".equals(type) || "ROCKETMQ".equals(type) || "RABBITMQ".equals(type) || "PULSAR".equals(type) || "PULSARMQ".equals(type) || "LOGGER".equals(type)) {
            return "logger";
        }
        if ("REDIS".equals(type)) {
            return "custom-redis";
        }
        if ("HBASE".equals(type)) {
            return "hbase";
        }
        if ("TABLESTORE".equals(type)) {
            return "tablestore";
        }
        return "rdb";
    }

    private static String mappingContent(String type, SyncTask task, DatasourceConfig datasource,
                                         List<TaskFieldMapping> mappings, Map<String, String> config, String key) {
        if ("LOGGER".equals(type)) {
            return "# logger target does not require mapping file\n";
        }
        if ("KAFKA".equals(type)) {
            return mqContract("kafka", datasource, task, mappings,
                    "bootstrapServers: " + valueOrDefault(config.get("bootstrapServers"), valueOrDefault(config.get("servers"), "127.0.0.1:9092")),
                    config);
        }
        if ("ROCKETMQ".equals(type)) {
            return mqContract("rocketmq", datasource, task, mappings,
                    "nameServer: " + valueOrDefault(config.get("nameServer"), valueOrDefault(config.get("namesrvAddr"), "127.0.0.1:9876")) + "\n"
                            + "producerGroup: " + valueOrDefault(config.get("producerGroup"), "canal-web-producer"),
                    config);
        }
        if ("RABBITMQ".equals(type)) {
            return mqContract("rabbitmq", datasource, task, mappings,
                    "host: " + valueOrDefault(config.get("host"), "127.0.0.1") + "\n"
                            + "port: " + valueOrDefault(config.get("port"), "5672") + "\n"
                            + "virtualHost: " + valueOrDefault(config.get("virtualHost"), "/") + "\n"
                            + "exchange: " + value(config.get("exchange")) + "\n"
                            + "routingKey: " + value(config.get("routingKey")),
                    config);
        }
        if ("PULSAR".equals(type) || "PULSARMQ".equals(type)) {
            return mqContract("pulsar", datasource, task, mappings,
                    "serviceUrl: " + valueOrDefault(config.get("serviceUrl"), valueOrDefault(config.get("serverUrl"), "pulsar://127.0.0.1:6650")) + "\n"
                            + "subscriptionName: " + valueOrDefault(config.get("subscriptionName"), valueOrDefault(config.get("consumerGroup"), "canal-web-subscription")),
                    config);
        }
        if ("HBASE".equals(type)) {
            return """
                    dataSourceKey: %s
                    destination: %s
                    groupId: g1
                    outerAdapterKey: %s
                    hbaseMapping:
                      mode: %s
                      database: %s
                      table: %s
                      hbaseTable: %s
                      family: %s
                      uppercaseQualifier: %s
                      rowKey: %s
                      etlCondition: "%s"
                      commitBatch: %s
                    columns:
                    %s
                    """.formatted(
                    datasource.dataSourceKey(),
                    datasource.canalDestination(),
                    key,
                    valueOrDefault(config.get("mode"), "STRING"),
                    datasource.dbName(),
                    valueOrDefault(config.get("sourceTable"), sourceTable(task.syncSql())),
                    valueOrDefault(config.get("hbaseTable"), valueOrDefault(config.get("tableName"), "default:" + sourceTable(task.syncSql()))),
                    valueOrDefault(config.get("family"), "CF"),
                    valueOrDefault(config.get("uppercaseQualifier"), "true"),
                    valueOrDefault(config.get("rowKey"), "id"),
                    valueOrDefault(config.get("etlCondition"), ""),
                    valueOrDefault(config.get("commitBatch"), "3000"),
                    hbaseColumns(mappings, valueOrDefault(config.get("rowKey"), "id"))
            );
        }
        if ("REDIS".equals(type)) {
            return """
                    # Redis is not an official Canal Adapter plugin in this runtime.
                    # This file is generated as a custom plugin contract for later extension.
                    destination: %s
                    groupId: g1
                    target:
                      type: redis
                      mode: %s
                      host: %s
                      port: %s
                      database: %s
                      keyPattern: %s
                      valueType: %s
                      valueMapping: %s
                      ttlSeconds: %s
                      deletePolicy: %s
                    source:
                      dataSourceKey: %s
                      database: %s
                      table: %s
                      sql: "%s"
                    columns:
                    %s
                    """.formatted(
                    datasource.canalDestination(),
                    valueOrDefault(config.get("redisMode"), "standalone"),
                    valueOrDefault(config.get("host"), "127.0.0.1"),
                    valueOrDefault(config.get("port"), "6379"),
                    valueOrDefault(config.get("database"), "0"),
                    valueOrDefault(config.get("keyPattern"), legacyRedisKeyPattern(config)),
                    valueOrDefault(config.get("valueType"), "HASH"),
                    value(config.get("valueMapping")),
                    valueOrDefault(config.get("ttlSeconds"), valueOrDefault(config.get("expireSeconds"), "0")),
                    valueOrDefault(config.get("deletePolicy"), "DELETE_KEY"),
                    datasource.dataSourceKey(),
                    datasource.dbName(),
                    valueOrDefault(config.get("sourceTable"), sourceTable(task.syncSql())),
                    inlineSql(task.syncSql()),
                    mappingColumns(mappings)
            );
        }
        if ("ES".equals(type) || "ELASTICSEARCH".equals(type)) {
            if ("custom-es".equals(valueOrDefault(config.get("adapterName"), "es8"))) {
                return """
                        destination: %s
                        groupId: g1
                        target:
                          type: elasticsearch
                          hosts: %s
                          index: %s
                          documentId: %s
                          deletePolicy: %s
                        source:
                          dataSourceKey: %s
                          database: %s
                          table: %s
                          sql: "%s"
                        columns:
                        %s
                        """.formatted(
                        datasource.canalDestination(),
                        normalizeEsHosts(config.get("hosts")),
                        valueOrDefault(config.get("index"), valueOrDefault(config.get("indexName"), task.taskName())),
                        normalizeEsDocumentId(config),
                        valueOrDefault(config.get("deletePolicy"), "DELETE_DOCUMENT"),
                        datasource.dataSourceKey(),
                        datasource.dbName(),
                        valueOrDefault(config.get("sourceTable"), sourceTable(task.syncSql())),
                        inlineSql(task.syncSql()),
                        mappingColumns(mappings)
                );
            }
            return """
                    dataSourceKey: %s
                    destination: %s
                    groupId: g1
                    outerAdapterKey: %s
                    esMapping:
                      _index: %s
                      _id: %s
                      pk: %s
                      upsert: %s
                      writeMode: %s
                      deletePolicy: %s
                      sql: "%s"
                      etlCondition: "%s"
                      commitBatch: %s
                      mapping: |-
                    %s
                    """.formatted(
                    datasource.dataSourceKey(),
                    datasource.canalDestination(),
                    key,
                    valueOrDefault(config.get("indexName"), valueOrDefault(config.get("index"), task.taskName())),
                    normalizeEsDocumentId(config),
                    valueOrDefault(config.get("primaryKey"), valueOrDefault(config.get("targetPk"), valueOrDefault(config.get("idField"), "id"))),
                    valueOrDefault(config.get("upsert"), "false"),
                    valueOrDefault(config.get("writeMode"), "UPSERT"),
                    valueOrDefault(config.get("deletePolicy"), "DELETE_DOCUMENT"),
                    inlineSql(task.syncSql()),
                    valueOrDefault(config.get("etlCondition"), ""),
                    valueOrDefault(config.get("commitBatch"), "3000"),
                    indentBlock(valueOrDefault(config.get("mapping"), "{}"), "    ")
            );
        }
        if ("TABLESTORE".equals(type)) {
            return """
                    dataSourceKey: %s
                    destination: %s
                    groupId: g1
                    outerAdapterKey: %s
                    tablestoreMapping:
                      endpoint: %s
                      instanceName: %s
                      tableName: %s
                      primaryKey: %s
                      writeMode: %s
                      deletePolicy: %s
                      commitBatch: %s
                      sql: "%s"
                    columns:
                    %s
                    """.formatted(
                    datasource.dataSourceKey(),
                    datasource.canalDestination(),
                    key,
                    value(config.get("endpoint")),
                    value(config.get("instanceName")),
                    valueOrDefault(config.get("tableName"), valueOrDefault(config.get("targetTable"), "target_table")),
                    valueOrDefault(config.get("primaryKey"), "id"),
                    valueOrDefault(config.get("writeMode"), "UPSERT"),
                    valueOrDefault(config.get("deletePolicy"), "DELETE_ROW"),
                    valueOrDefault(config.get("commitBatch"), "200"),
                    inlineSql(task.syncSql()),
                    mappingColumns(mappings)
            );
        }
        List<TaskFieldMapping> enabledMappings = enabledMappings(mappings);
        String targetColumns = enabledMappings.isEmpty()
                ? "    id:\n"
                : enabledMappings.stream().map(item -> "    " + item.targetField() + ":").collect(Collectors.joining("\n"));
        String targetPk = valueOrDefault(config.get("primaryKey"), valueOrDefault(config.get("targetPk"), "id"));
        String targetTable = valueOrDefault(config.get("targetTableName"),
                valueOrDefault(config.get("targetTable"), valueOrDefault(config.get("sourceTable"), "target_table")));
        return """
                dataSourceKey: %s
                destination: %s
                groupId: g1
                outerAdapterKey: %s
                concurrent: true
                dbMapping:
                  database: %s
                  table: %s
                  targetTable: %s
                  writeMode: %s
                  targetPk:
                    %s: %s
                  targetColumns:
                %s
                  fieldOptions:
                %s
                  etlCondition: "%s"
                  commitBatch: %s
                """.formatted(
                datasource.dataSourceKey(),
                datasource.canalDestination(),
                key,
                datasource.dbName(),
                valueOrDefault(config.get("sourceTable"), sourceTable(task.syncSql())),
                targetTable,
                valueOrDefault(config.get("writeMode"), "UPSERT"),
                targetPk,
                targetPk,
                targetColumns,
                fieldOptionsBlock(enabledMappings, "    "),
                valueOrDefault(config.get("etlCondition"), ""),
                valueOrDefault(config.get("commitBatch"), "3000")
        );
    }

    private static String sourceTable(String sql) {
        if (sql == null) {
            return "source_table";
        }
        String lower = sql.toLowerCase();
        int from = lower.indexOf(" from ");
        if (from < 0) {
            return "source_table";
        }
        String tail = sql.substring(from + 6).trim();
        if (tail.isBlank()) {
            return "source_table";
        }
        return tail.split("\\s+")[0].replace("`", "");
    }

    private static String mqContract(String type, DatasourceConfig datasource, SyncTask task, List<TaskFieldMapping> mappings,
                                     String endpointBlock, Map<String, String> config) {
        return """
                # %s producer contract generated for Canal MQ mode or downstream extension.
                destination: %s
                groupId: g1
                target:
                  type: %s
                  %s
                  topic: %s
                  messageKey: %s
                  partitionKey: %s
                  messageFormat: %s
                  consumerGroup: %s
                  retries: %s
                source:
                  dataSourceKey: %s
                  database: %s
                  table: %s
                  sql: "%s"
                columns:
                %s
                """.formatted(
                type,
                datasource.canalDestination(),
                type,
                endpointBlock.replace("\n", "\n  "),
                valueOrDefault(config.get("topic"), "canal-topic"),
                valueOrDefault(config.get("messageKey"), "{id}"),
                value(config.get("partitionKey")),
                valueOrDefault(config.get("messageFormat"), "JSON"),
                valueOrDefault(config.get("consumerGroup"), value(config.get("subscriptionName"))),
                valueOrDefault(config.get("retries"), "3"),
                datasource.dataSourceKey(),
                datasource.dbName(),
                valueOrDefault(config.get("sourceTable"), sourceTable(task.syncSql())),
                inlineSql(task.syncSql()),
                mappingColumns(mappings)
        );
    }

    private static String mappingColumns(List<TaskFieldMapping> mappings) {
        List<TaskFieldMapping> enabled = enabledMappings(mappings);
        if (enabled.isEmpty()) {
          return "  - id";
        }
        return enabled.stream()
                .map(item -> "  - " + item.sourceField() + ": " + item.targetField() + fieldInlineOptions(item))
                .collect(Collectors.joining("\n"));
    }

    private static String hbaseColumns(List<TaskFieldMapping> mappings, String rowKey) {
        List<TaskFieldMapping> enabled = enabledMappings(mappings);
        if (enabled.isEmpty()) {
            return "    id: ROWKEY\n";
        }
        String normalizedRowKey = valueOrDefault(rowKey, "id").split(",")[0].trim();
        return enabled.stream()
                .map(item -> {
                    String qualifier = item.targetField() == null || item.targetField().isBlank()
                            ? item.sourceField()
                            : item.targetField();
                    String suffix = item.sourceField().equals(normalizedRowKey) || Boolean.TRUE.equals(item.primaryKey()) ? " ROWKEY" : "";
                    suffix += fieldInlineOptions(item);
                    return "    " + item.sourceField() + ": " + qualifier + suffix;
                })
                .collect(Collectors.joining("\n"));
    }

    private static String legacyRedisKeyPattern(Map<String, String> config) {
        String keyField = valueOrDefault(config.get("keyField"), "id");
        String keyPrefix = value(config.get("keyPrefix"));
        return keyPrefix.isBlank() ? "{" + keyField + "}" : keyPrefix + ":{" + keyField + "}";
    }

    private static String indentBlock(String text, String prefix) {
        return valueOrDefault(text, "").lines()
                .map(line -> prefix + line)
                .collect(Collectors.joining("\n"));
    }

    private static List<TaskFieldMapping> enabledMappings(List<TaskFieldMapping> mappings) {
        if (mappings == null) {
            return List.of();
        }
        return mappings.stream()
                .filter(item -> item.enabled() == null || Boolean.TRUE.equals(item.enabled()))
                .toList();
    }

    private static String fieldOptionsBlock(List<TaskFieldMapping> mappings, String prefix) {
        List<TaskFieldMapping> enabled = enabledMappings(mappings);
        if (enabled.isEmpty()) {
            return "";
        }
        return enabled.stream()
                .map(item -> prefix + item.targetField() + ":\n" + fieldOptionLines(item, prefix + "  "))
                .collect(Collectors.joining("\n"));
    }

    private static String fieldOptionLines(TaskFieldMapping item, String prefix) {
        String base = List.of(
                        optionLine(prefix, "source", item.sourceField(), true),
                        optionLine(prefix, "target", item.targetField(), true),
                        optionLine(prefix, "type", item.fieldType(), true),
                        optionLine(prefix, "primaryKey", String.valueOf(Boolean.TRUE.equals(item.primaryKey())), false),
                        optionLine(prefix, "nullable", String.valueOf(item.nullableField() == null || Boolean.TRUE.equals(item.nullableField())), false),
                        optionLine(prefix, "defaultValue", item.defaultValue(), true),
                        optionLine(prefix, "transform", item.transformExpr(), true),
                        optionLine(prefix, "format", item.formatPattern(), true)
                ).stream()
                .filter(line -> !line.isBlank())
                .collect(Collectors.joining("\n"));
        String options = fieldOptionsYaml(item.fieldOptions(), prefix);
        if (base.isBlank()) {
            return options;
        }
        return options.isBlank() ? base : base + "\n" + options;
    }

    private static String fieldInlineOptions(TaskFieldMapping item) {
        String options = fieldOptionLines(item, " ")
                .replace("\n  ", ", ")
                .replace("\n ", ", ");
        return options.isBlank() ? "" : " # " + options.replace("\n ", ", ").trim();
    }

    private static String optionLine(String prefix, String key, String value, boolean quote) {
        if (value == null || value.isBlank()) {
            return "";
        }
        return quote ? prefix + key + ": \"" + escapeYaml(value) + "\"" : prefix + key + ": " + value;
    }

    private static String fieldOptionsYaml(String value, String prefix) {
        Map<String, Object> options = fieldOptions(value);
        if (options.isEmpty()) {
            return "";
        }
        String body = options.entrySet().stream()
                .map(entry -> prefix + "  " + entry.getKey() + ": " + yamlValue(entry.getValue()))
                .collect(Collectors.joining("\n"));
        return prefix + "options:\n" + body;
    }

    private static String yamlValue(Object value) {
        if (value == null) {
            return "null";
        }
        if (value instanceof Number || value instanceof Boolean) {
            return String.valueOf(value);
        }
        return "\"" + escapeYaml(String.valueOf(value)) + "\"";
    }

    private static Map<String, Object> fieldOptions(String value) {
        if (value == null || value.isBlank()) {
            return Map.of();
        }
        try {
            Map<String, Object> parsed = OBJECT_MAPPER.readValue(value, new TypeReference<>() {
            });
            return new LinkedHashMap<>(parsed);
        } catch (Exception ex) {
            return Map.of("raw", value);
        }
    }

    private static String defaultDriver(String type) {
        return switch (type) {
            case "PGSQL", "POSTGRESQL" -> "org.postgresql.Driver";
            case "ORACLE" -> "oracle.jdbc.OracleDriver";
            default -> "com.mysql.jdbc.Driver";
        };
    }

    private static String defaultJdbcUrl(String type) {
        return switch (type) {
            case "PGSQL", "POSTGRESQL" -> "jdbc:postgresql://127.0.0.1:5432/postgres";
            case "ORACLE" -> "jdbc:oracle:thin:@127.0.0.1:1521:XE";
            default -> "jdbc:mysql://127.0.0.1:3306/target?useUnicode=true&characterEncoding=utf8&useSSL=false";
        };
    }

    private static String inlineSql(String sql) {
        return valueOrDefault(sql, "select * from source_table").replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", " ");
    }

    private static String indentSql(String sql) {
        String value = sql == null || sql.isBlank() ? "SELECT 1" : sql;
        return value.lines().map(line -> "  " + line).collect(Collectors.joining("\n"));
    }

    private static String escapeYaml(String value) {
        return value == null ? "" : value.replace("\"", "\\\"");
    }

    private static String normalizeEsHosts(String hosts) {
        String value = valueOrDefault(hosts, "127.0.0.1:9200");
        return java.util.Arrays.stream(value.split(","))
                .map(String::trim)
                .filter(item -> !item.isBlank())
                .map(item -> item.contains("://") ? item : "http://" + item)
                .collect(Collectors.joining(","));
    }

    private static String normalizeEsDocumentId(Map<String, String> config) {
        String documentId = valueOrDefault(config.get("documentId"), valueOrDefault(config.get("idField"), "id"));
        if (documentId.startsWith("{") && documentId.endsWith("}") && documentId.length() > 2) {
            return documentId.substring(1, documentId.length() - 1);
        }
        return documentId;
    }

    private static String value(String value) {
        return value == null ? "" : value;
    }

    private static String valueOrDefault(String value, String defaultValue) {
        return value == null || value.isBlank() ? defaultValue : value;
    }

    public record AdapterRuntimeFiles(String destination, String outerAdapterBlock, String mappingDir, String mappingFile,
                                      String mappingContent) {
    }
}
